version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: bd_productos
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"